name: Cypress tests
on:
  pull_request:
  push:
    branches:
      - master
    
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: e2e
      - name: Start server in the background
        run: npm run dev &
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: e2e
          browser: chrome
          # NOTE: Wait load images.
          command-prefix: 'percy exec --network-idle-timeout=1000 -- npx'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
